### ISSUE TITLE
authType JWT not working

### ISSUE THREAD

**Issue by rxd2** [docusign/sample-app-myhr-csharp#51]
"Log in with a test account" is not working both on a live example site and locally.

Go here https://myhr.sampleapps.docusign.com and click "Log in with a test account"
https://myhr.sampleapps.docusign.com/Account/Login?authType=JWT
returns {"StatusCode":500,"Message":"Internal Server Error."}

Same error message when running the solution locally. The internal error is  {"error":"consent_required"}. 
I tried granting my login the consent as described here 
https://www.docusign.com/blog/developers/oauth-jwt-granting-consent
but it did not change anything.

**Comment by InbarGazit** [comment]
Thanks for the report, we're on it!

**Comment by InbarGazit** [comment]
BTW, since you run it locally, you do need consent @rxd2 because you will not be using our own account, you will be using your IK+account/user. Did you obtain consent?

**Comment by InbarGazit** [comment]
https://developers.docusign.com/platform/auth/consent/obtaining-individual-consent

**Comment by rxd2** [comment]
Yes, I did. The link you provided has the same instructions for getting consent as I included in the issue description https://www.docusign.com/blog/developers/oauth-jwt-granting-consent

**Comment by InbarGazit** [comment]
This issue is now fixed, it's working both on local and on the posted server

**Comment by InbarGazit** [comment]
https://github.com/docusign/sample-app-myhr-csharp/pull/52 fixed it

**Comment by InbarGazit** [comment]
The issue was related to docker. Running without Docker container worked ok

**Comment by rxd2** [comment]
JFYI, my local issue was that the demo app RequestJWTUserToken requests 2 scopes: click.manage and signature.
DocuSign instructions for getting consent include signature and impersonation scopes. So you need to add click.manage when constructing the consent URL. 
scope=signature%20impersonation%20click.manage

**Comment by InbarGazit** [comment]
The instructions maybe we can improve, for JWT you always need impersonation, but the other two are what's needed for this app, for Auth Code Grant, and then you always add `impersonation` for JWT

**Comment by InbarGazit** [comment]
Does it work for you now?

**Comment by rxd2** [comment]
Yes, thanks.
